# Generated by Django 3.0.7 on 2020-06-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='images/')),
                ('dateadded', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('quarantine', 'Quarantine related'), ('stigma', 'Stigma related'), ('testing', 'Testing related')], default='stigma', max_length=32)),
            ],
        ),
    ]
