# Generated by Django 3.0.7 on 2020-06-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateadded']},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('QUARANTINE', 'Quarantine related'), ('STIGMA', 'Stigma related'), ('TESTING', 'Testing related')], default='STIGMA', max_length=32),
        ),
    ]
